# Generated by Django 5.2.11 on 2026-02-26 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkin_sessions", "0001_initial"),
        ("faces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("matched", models.BooleanField(default=False)),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_face_image",
                    models.ImageField(
                        help_text="Raw face image captured at check-in time, stored for audit.",
                        upload_to="checkins/images/",
                    ),
                ),
                (
                    "face",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null when the attempt did not match any enrolled face.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins",
                        to="faces.face",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="checkin_sessions.session",
                    ),
                ),
            ],
            options={
                "ordering": ["-checked_in_at"],
            },
        ),
    ]
