# Generated by Django 5.2.11 on 2026-03-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0001_initial"),
        ("checkin_sessions", "0001_initial"),
        ("faces", "0002_alter_face_options_alter_facegroup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checkin",
            options={
                "ordering": ["-checked_in_at"],
                "verbose_name": "การเช็กอิน",
                "verbose_name_plural": "การเช็กอิน",
            },
        ),
        migrations.AddField(
            model_name="checkin",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP ที่ใช้เช็กอิน"),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="checked_in_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="เวลาเช็กอิน"),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="face",
            field=models.ForeignKey(
                blank=True,
                help_text="ว่างเปล่าเมื่อไม่พบใบหน้าที่ตรงกัน",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkins",
                to="faces.face",
                verbose_name="ใบหน้า",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="matched",
            field=models.BooleanField(default=False, verbose_name="ตรงกัน"),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="raw_face_image",
            field=models.ImageField(
                help_text="ภาพใบหน้าที่ถ่ายขณะเช็กอิน เก็บไว้เพื่อตรวจสอบ",
                upload_to="checkins/images/",
                verbose_name="ภาพใบหน้า",
            ),
        ),
        migrations.AlterField(
            model_name="checkin",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="checkin_sessions.session",
                verbose_name="คาบเรียน",
            ),
        ),
    ]
