# Generated by Django 5.2.11 on 2026-03-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin", "0002_add_ip_address_to_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkin",
            name="user_agent",
            field=models.TextField(blank=True, default="", verbose_name="User Agent"),
        ),
    ]
