# Generated by Django 5.2.11 on 2026-03-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_class_shorthand"),
        ("faces", "0002_alter_face_options_alter_facegroup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "วิชา",
                "verbose_name_plural": "วิชา",
            },
        ),
        migrations.AlterModelOptions(
            name="classtag",
            options={
                "ordering": ["tag"],
                "verbose_name": "แท็กวิชา",
                "verbose_name_plural": "แท็กวิชา",
            },
        ),
        migrations.AlterField(
            model_name="class",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
        ),
        migrations.AlterField(
            model_name="class",
            name="description",
            field=models.TextField(blank=True, verbose_name="คำอธิบาย"),
        ),
        migrations.AlterField(
            model_name="class",
            name="face_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classes",
                to="faces.facegroup",
                verbose_name="กลุ่มใบหน้า",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อวิชา"),
        ),
        migrations.AlterField(
            model_name="class",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
        ),
        migrations.AlterField(
            model_name="classtag",
            name="klass",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="classes.class",
                verbose_name="วิชา",
            ),
        ),
        migrations.AlterField(
            model_name="classtag",
            name="tag",
            field=models.CharField(max_length=100, verbose_name="แท็ก"),
        ),
    ]
