# Generated by Django 5.2.11 on 2026-03-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin_sessions", "0001_initial"),
        ("classes", "0002_class_shorthand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "คาบเรียน",
                "verbose_name_plural": "คาบเรียน",
            },
        ),
        migrations.AlterField(
            model_name="session",
            name="auto_close_at",
            field=models.DateTimeField(
                blank=True,
                help_text="หากกำหนดไว้ คาบเรียนจะปิดโดยอัตโนมัติเมื่อถึงเวลานี้",
                null=True,
                verbose_name="ปิดอัตโนมัติเมื่อ",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
        ),
        migrations.AlterField(
            model_name="session",
            name="klass",
            field=models.ForeignKey(
                db_column="class_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="classes.class",
                verbose_name="วิชา",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อคาบเรียน"),
        ),
        migrations.AlterField(
            model_name="session",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="เวลาเริ่มต้นที่กำหนด (ข้อมูลอ้างอิง)",
                null=True,
                verbose_name="เวลาเริ่มต้น",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="state",
            field=models.CharField(
                choices=[("active", "เปิดให้เช็กอิน"), ("closed", "ปิดไม่ให้เช็กอิน")],
                default="active",
                max_length=10,
                verbose_name="สถานะ",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
        ),
    ]
