# Generated by Django 5.2.11 on 2026-04-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkin_sessions", "0003_rename_klass_to_course"),
        ("classes", "0005_rename_class_to_course"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="session",
                    name="course",
                    field=models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="classes.course",
                        verbose_name="วิชา",
                    ),
                ),
            ],
        ),
    ]
