# Generated by Django 5.2.11 on 2026-02-26 04:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "custom_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Unique identifier within the face group. Defaults to a UUID.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("remarks", models.TextField(blank=True)),
                (
                    "embedding",
                    models.BinaryField(
                        blank=True,
                        help_text="128-d face embedding vector stored as raw float32 bytes.",
                        null=True,
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="faces/photos/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "face_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="faces.facegroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("face_group", "custom_id")},
            },
        ),
    ]
