# Generated by Django 5.2.11 on 2026-03-28 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faces", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="face",
            options={"ordering": ["name"], "verbose_name": "ใบหน้า", "verbose_name_plural": "ใบหน้า"},
        ),
        migrations.AlterModelOptions(
            name="facegroup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "กลุ่มใบหน้า",
                "verbose_name_plural": "กลุ่มใบหน้า",
            },
        ),
        migrations.AlterField(
            model_name="face",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
        ),
        migrations.AlterField(
            model_name="face",
            name="custom_id",
            field=models.CharField(
                help_text="รหัสเฉพาะภายในกลุ่มใบหน้า", max_length=255, verbose_name="รหัสประจำตัว"
            ),
        ),
        migrations.AlterField(
            model_name="face",
            name="embedding",
            field=models.BinaryField(
                blank=True,
                help_text="เวกเตอร์ข้อมูลใบหน้า 128 มิติ เก็บเป็น float32 bytes",
                null=True,
                verbose_name="ข้อมูลใบหน้า",
            ),
        ),
        migrations.AlterField(
            model_name="face",
            name="face_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faces",
                to="faces.facegroup",
                verbose_name="กลุ่มใบหน้า",
            ),
        ),
        migrations.AlterField(
            model_name="face",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อ"),
        ),
        migrations.AlterField(
            model_name="face",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="faces/photos/", verbose_name="รูปภาพ"
            ),
        ),
        migrations.AlterField(
            model_name="face",
            name="remarks",
            field=models.TextField(blank=True, verbose_name="หมายเหตุ"),
        ),
        migrations.AlterField(
            model_name="face",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="แก้ไขล่าสุด"),
        ),
        migrations.AlterField(
            model_name="facegroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="สร้างเมื่อ"),
        ),
        migrations.AlterField(
            model_name="facegroup",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อกลุ่ม"),
        ),
    ]
