# Generated by Django 5.2.11 on 2026-04-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faces", "0002_alter_face_options_alter_facegroup_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="facegroup",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_face_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของ",
            ),
        ),
        migrations.AddField(
            model_name="facegroup",
            name="shared_with_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="shared_face_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="แชร์กับผู้ใช้",
            ),
        ),
    ]
